### ISSUE TITLE
POE version

### ISSUE THREAD

**Issue by ishioni** [ThomasVon2021/pikvm-CM4-Board#1]
Is a poe-powered version a possibility?

**Comment by ThomasVon2021** [comment]
The current version doesn't support it for the time being. The POE function has been taken into account in the later version. Please look forward to it. Attach recent test videos：https://www.youtube.com/watch?v=aehOawHklGE

**Comment by 12nick12** [comment]
Any idea on the time frame for a PoE version? I'm looking to purchase, but wouldn't mind holding off a month or two for a PoE version.

**Comment by hzzfly** [comment]
POE version takes about 3 months



At 2022-02-04 11:07:34, "Nick Leffler" ***@***.***> wrote:

Any idea on the time frame for a PoE version? I'm looking to purchase, but wouldn't mind holding off a month or two for a PoE version.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 12nick12** [comment]
OK, awesome, I can't wait.
