### ISSUE TITLE
Request for clarity in documentation - USB OTG for control?

### ISSUE THREAD

**Issue by geerlingguy** [ThomasVon2021/pikvm-CM4-Board#11]
I'm assuming (but would like to know if my assumption is correct) that to control a PC's USB interface, you would plug a USB-C to USB-A cable from the USB-C 'OTG' port on the BliKVM into a USB-A port on the PC you're controlling?

It wasn't 100% clear in the documentation, but that seems the logical place, and the current description kind of says that but not explicitly:

> ## 2.4. USB-C OTG
>
> This port is doing the emulation of a USB keyboard, mouse, Virtual CD-ROM or USB Flash Drive, USB-Ethernet, USB-Serial port and a lot of other Linux-supported features. This interface cannot provide external power.

**Comment by hzzfly** [comment]
Yes you are right ,We update the manual according to your suggestion



At 2022-01-31 06:45:44, "Jeff Geerling" ***@***.***> wrote:

I'm assuming (but would like to know if my assumption is correct) that to control a PC's USB interface, you would plug a USB-C to USB-A cable from the USB-C 'OTG' port on the BliKVM into a USB-A port on the PC you're controlling?

It wasn't 100% clear in the documentation, but that seems the logical place, and the current description kind of says that but not explicitly:

2.4. USB-C OTG

This port is doing the emulation of a USB keyboard, mouse, Virtual CD-ROM or USB Flash Drive, USB-Ethernet, USB-Serial port and a lot of other Linux-supported features. This interface cannot provide external power.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThomasVon2021** [comment]
According to your suggestion, we have added relevant description. Thank you very much.
