### ISSUE TITLE
Documentation - Compute Modules with eMMC can't boot from SD

### ISSUE THREAD

**Issue by vesrah** [ThomasVon2021/pikvm-CM4-Board#12]
Hi, I think it is worth noting somewhere on the documentation that using a CM4 with eMMC requires flashing the image with your instructions at https://github.com/ThomasVon2021/pikvm-CM4-Board/wiki to boot.  I was a little confused by the no-boot with red and green lights lit up until I joined your Skype and scrolled up to find this information.

Thanks!

**Comment by ThomasVon2021** [comment]
Do you mean if someone use cm4 with eMMC,he maybe boot form sd? So the documentation need add this instructions.

**Comment by vesrah** [comment]
If someone uses a CM4 with eMMC they need to use https://github.com/ThomasVon2021/pikvm-CM4-Board/wiki instead of flashing an SD and inserting it into the BliKVM.  I think the documentation just needs to have this note for people with eMMC.

**Comment by ThomasVon2021** [comment]
i understand,thank you.i will accpet your suggestion.
