### ISSUE TITLE
Activity LED always solid green?

### ISSUE THREAD

**Issue by geerlingguy** [ThomasVon2021/pikvm-CM4-Board#15]
I noticed on my BliKVM, the ACT LED is always solid green; it doesn't seem to correctly indicate any status on the board. On other CM4 boards and the IO board, it seems to flash to indicate eMMC/microSD card access, but on the BliKVM it's always green when running the PiKVM image.

I noticed on the image it sets:

```
dtparam=act_led_gpio=13
```

Does that parameter need to be changed to make the LED work correctly?

**Comment by hzzfly** [comment]
Delete this code
`dtparam=act_led_gpio=13`
to make the LED work correctly

**Comment by ThomasVon2021** [comment]
Hello, geerlingguy we receive many person test it ok. So we decide to close this issue.

**Comment by geerlingguy** [comment]
@ThomasVon2021 - So the process for me was to log in via SSH as root, then:

  1. `rw` to set read write mode
  2. Edit `/boot/config.txt`
  3. Delete `dtparam=act_led_gpio=13` from the file and save
  4. `reboot` to reboot immediately

Should this be added maybe on the Wiki under the Activity LED section?
