### ISSUE TITLE
Getting WiFi working?

### ISSUE THREAD

**Issue by geerlingguy** [ThomasVon2021/pikvm-CM4-Board#16]
I was wondering if anyone else has gotten WiFi working following PiKVM's guide: https://docs.pikvm.org/wifi/

I noticed that `dtoverlay=disable-bt` is enabled in the PiKVM image `/boot/config.txt` file, but if I comment out that line and reboot, I can't get the Pi to boot at all anymore :/

**Comment by durankeeley** [comment]
That is weird when I did my pikvm I did the wifi in the first steps and that worked. 

https://docs.pikvm.org/first_steps/#first-power-on

**Comment by geerlingguy** [comment]
To be honest I didn't try that method :D

I tried setting up WiFi after the first boot, following the docs I linked to, and had trouble there.

**Comment by ThomasVon2021** [comment]
> To be honest I didn't try that method :D
> 
> I tried setting up WiFi after the first boot, following the docs I linked to, and had trouble there.

Excuse me, have you solved this problem? If not, I will test again

**Comment by PhilipTS** [comment]
I am also having this issue. I got a CM4 with eMMC 16GB and WiFi (all I could find).
After spending a day trying with an sdcard i read that i have to exclusively use the eMMC. (my first CM4).

I got everything working and I decided to give WiFi a try.
I just can't get it to work. I don't even see the device in ifconfig.

**Comment by arjanwaard** [comment]
Check https://askubuntu.com/questions/1326027/raspberry-pi-4-compute-module-4-cm4-no-wifi-with-ubuntu-20-04-server
Looks like the same issue
Just cd to /lib/firmware/brcm
rw and "ln -s brcmfmac43455-sdio.raspberrypi,4-model-b.txt brcmfmac43455-sdio.raspberrypi,4-compute-module.txt" should probably fix it

**Comment by arjanwaard** [comment]
modprobe brcmfmac
modprobe brcmutil
indeed now gives a link visible with "ip link" 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether dc:a6:32:fe:d3:eb brd ff:ff:ff:ff:ff:ff
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 500
    link/none 
5: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether dc:a6:32:fe:d3:ec brd ff:ff:ff:ff:ff:ff

**Comment by PhilipTS** [comment]
@arjanwaard Thank You ... you were spot on ...

````
[root@pikvm brcm]# dmesg | grep brcmfmac
[    9.403488] brcmfmac: F1 signature read @0x18000000=0x15264345
[    9.408782] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.433063] usbcore: registered new interface driver brcmfmac
[    9.478935] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.txt failed with error -2
[   10.509914] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50


ln -s brcmfmac43455-sdio.raspberrypi,4-model-b.txt brcmfmac43455-sdio.txt

reboot

[root@pikvm ~]# dmesg | grep brcmfmac
[    9.484862] brcmfmac: F1 signature read @0x18000000=0x15264345
[    9.493202] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.507221] usbcore: registered new interface driver brcmfmac
[    9.739061] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.750276] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.776707] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Apr 15 2021 03:03:20 version 7.45.234 (4ca95bb CY) FWID 01-996384e2
[    9.908705] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled


[root@pikvm ~]# dmesg | grep brcmfmac
[    9.484862] brcmfmac: F1 signature read @0x18000000=0x15264345
[    9.493202] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.507221] usbcore: registered new interface driver brcmfmac
[    9.739061] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.750276] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.776707] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Apr 15 2021 03:03:20 version 7.45.234 (4ca95bb CY) FWID 01-996384e2
[    9.908705] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
````

**Comment by PhilipTS** [comment]
@ThomasVon2021 it would be good if you included the above in the wiki somewhere, how to enable WiFi.

**Comment by ThomasVon2021** [comment]
The wifi problem has been solved.See:
https://github.com/ThomasVon2021/pikvm-CM4-Board/wiki#setting-up-wi-fi
