### ISSUE TITLE
Mutiple board versions confusion

### ISSUE THREAD

**Issue by s12321** [ThomasVon2021/pikvm-CM4-Board#3]
The current board version is confusing. I've found v2.1, v2.2 and v3 from this website, which one is the updated one. 
https://www.aliexpress.com/item/1005003262886521.html

Where is the official sale website? Thanks

**Comment by ThomasVon2021** [comment]
This is our official sales website. The information on Ali has not been updated since we have been iterating recently. We will update it recently and attach the latest test video：https://www.youtube.com/watch?v=aehOawHklGE
