### ISSUE TITLE
Can I use BLIKVM to flash eMMC?

### ISSUE THREAD

**Issue by thesuperzapper** [ThomasVon2021/pikvm-CM4-Board#6]
My CM4 has 16GB of eMMC storage, so I would like to use that instead of an SD card.

Can I use the BLIKVM board to flash the eMMC storage using [`rpiboot`](https://github.com/raspberrypi/usbboot
), or will I need a [Compute Module 4 IO Board](https://www.raspberrypi.com/products/compute-module-4-io-board/) as describe [here](https://www.jeffgeerling.com/blog/2020/how-flash-raspberry-pi-os-compute-module-4-emmc-usbboot)?

**Comment by arjanwaard** [comment]
You can ! Just did it on mine. Took a long time but worked fine, use the OTG port to connect the device to your computer and make sure to put the header on usbboot on the board.

**Comment by ThomasVon2021** [comment]
https://github.com/ThomasVon2021/pikvm-CM4-Board/wiki#flashing-the-os-image
I have added this detailed description
